version: 0.1.{build}

os: Windows Server 2012 R2

platform: x64

environment:
  matrix:
  - TOOLCHAIN: "cygwin"

branches:
  only:
    - master

skip_tags: true

install:
  - C:\cygwin64\setup-x86_64.exe -qnNdO -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P libbz2-devel -P zlib-devel -P liblzma-devel -P libiconv-devel

build_script:
  - C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/librdata && ./autogen.sh"
  - C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/librdata && ./configure"
  - C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/librdata && make"

test_script:
  - C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/librdata && make check"

on_finish:
  - C:\cygwin64\bin\sh -lc "cd /cygdrive/c/projects/librdata && cat ./test-suite.log"
