name: build
on: [ push, pull_request ]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ clang, gcc ]
    steps:
      - name: Install packages
        run: sudo apt install gettext
      - uses: actions/checkout@v2
      - name: Autoconf
        run: autoreconf -i -f
      - name: Configure
        run: ./configure
      - name: Make
        run: make
      - name: Tests
        run: make check
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [ clang, gcc ]
    steps:
      - name: Install packages
        run: brew install automake
      - uses: actions/checkout@v2
      - name: Autoconf
        run: autoreconf -i -f
      - name: Configure
        run: ./configure
      - name: Make
        run: make
      - name: Tests
        run: make check
